### ISSUE TITLE
Pivot data in ASP Core 6 demo

### ISSUE THREAD

**Issue by fasteddys** [roadrunnerlenny/etlboxdemo#3]
Hello can you please share samples on using ETLbox with a UI inside asp core.

How much is the license

**Comment by andreaslennartz** [comment]
Hi @fasteddys ,

thanks for reaching out.
Please see the following example code which shows how to pivot data: https://www.etlbox.net/recipes/etl/pivot-data/

ETLBox supports .NET Standard 2.0, so it will work with .NET Core and all current .NET versions (e.g. .NET 5 and .NET 6).
Simple add a reference to the nuget package in  your .NET project.

Read more about pricing and licensing here: [www.etlbox.net/pricing](https://www.etlbox.net/pricing?utm_source=github&utm_content=demo)

Let me know if you have any additional questions!
